### ISSUE TITLE
Work with "baseUrl"

### ISSUE THREAD

**Issue by rifler** [OniVe/ts-transform-paths#15]
Hi!

I specify only `"baseUrl": "."` without `"paths"` and import modules like so:
```ts
import {} from 'server/router';
```

I think it would be great to support this kind of usage, like https://github.com/dividab/tsconfig-paths did

**Comment by OniVe** [comment]
It doesn't quite fit the original concept. Initially it was thought that it would be a regular script without side effects and without scanning the file system.

**Comment by rifler** [comment]
I found package, that meets my needs - https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths

thank you
