### ISSUE TITLE
Transformed unused imports are not removed

### ISSUE THREAD

**Issue by squidfunk** [OniVe/ts-transform-paths#20]
First of all, thanks for this awesome plugin. Together with `ttypescript` it really helps to keep import paths sane.

It seems that when the plugin updates a type declaration, the import paths are kept in the emitted source files. This is true regardless of module. This is especially problematic when using `import type ...` declarations together with an `es2015` module target, as the emitted files will now include those declarations, which is invalid JavaScript.

This only happens when a path is actually replaced, for example:

``` ts
import type { A } from "../a" // <= this is removed
import type { A } from "~/a"  // <= this is kept
```
__
[import-repro.zip](https://github.com/OniVe/ts-transform-paths/files/5787898/import-repro.zip)

Possibily related issue: https://github.com/microsoft/TypeScript/issues/40603

**Comment by OniVe** [comment]
@squidfunk Thanks for PR :+1:

**Comment by squidfunk** [comment]
Thanks for merging and releasing this so quickly! 🙏
