### ISSUE TITLE
rootDir and outDir are not taken into account

### ISSUE THREAD

**Issue by emmkimme** [OniVe/ts-transform-paths#24]
Hi

likely my mistake, but I did not get it to work.

I have the following configuration (just keep relevant fields)
```
{
    "include": [
        "../../eikon-framework/src/**/*.ts"
    ],
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "df-core/*": ["./build/df-core/*"],
            "*": [
                "./node_modules/*",
                "./node_modules/@types/*"
            ]
        },
        "rootDir": "../../eikon-framework/src",
        "outDir": "./build/eikon-framework"
    }
}
```
I have the following file:
../../src/eikon-framework/src/auth/auth-impl.ts
`import { GetElectronEnvironment } from 'df-core/env';`

after the compilation in the outDir folder I have
[outDir]/eikon-framework/auth/auth-impl.js
`const env_1 = require("../../../products/workspace/build/df-core/env");`

It seems the resolution has been done from the original location of TS file and not from the output location of JS file.
With  "df-core/*": ["./build/df-core/*"] and outDir = ./build/eikon-framework/auth/auth-impl.js

I would expect
`const env_1 = require("../../df-core/env");`

Could you help me please

Thanks

**Comment by OniVe** [comment]
Hi!
The path `df-core/*` will be interpreted as a module.
Use paths with special characters, for example: `@df-core/*` or `~df-core/*`

**Comment by emmkimme** [comment]
Hi,
thanks for the suggestion, but in my case, it is not possible to change all sources imports.

may I say official typescript samples do not use special characters: https://www.typescriptlang.org/tsconfig#paths
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
        "app/*": ["app/*"],
        "config/*": ["app/_config/*"],
        "environment/*": ["environments/*"],
        "shared/*": ["app/_shared/*"],
        "helpers/*": ["helpers/*"],
        "tests/*": ["tests/*"]
    },
}
```
I understand it could be a limitation of the plugin but it would deserve a comment and your suggested workaround in the readme
Regards
