### ISSUE TITLE
Does not work with exports

### ISSUE THREAD

**Issue by roblav96** [OniVe/ts-transform-paths#3]
The paths for `exports` are not transformed.

#### Example:
```ts
export * from '@/adapters/http'
export { Http, HTTPError } from '@/adapters/http'
```

**Comment by OniVe** [comment]
Expected in version `2.0` like other features. Work in progress.

**Comment by OniVe** [comment]
Added in version [v2.0.0](https://github.com/OniVe/ts-transform-paths/releases/tag/v2.0.0)
