### ISSUE TITLE
Deprecation of the method: createStringLiteral

### ISSUE THREAD

**Issue by leoneves** [OniVe/ts-transform-paths#37]
I really appreciate this project. 
I believe that this warning is about this project.
Would be nice if you could update this = )
Thanks in advance.

DeprecationWarning: 'createStringLiteral' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.

![image](https://user-images.githubusercontent.com/798810/191351211-69008602-3df0-4ea3-aae3-d3f2df06e7b4.png)

**Comment by OniVe** [comment]
@leoneves This is a "breaking changes", property `ts.factory` does not exist in 'typescript^3.0.0'.
This will require an increase in the major version number.

**Comment by OniVe** [comment]
([438f552](https://github.com/OniVe/ts-transform-paths/commit/438f552a3beed033d7abfb4ddf7c5bf6fcef36f7))
